### ISSUE TITLE
Consider changing license

### ISSUE THREAD

**Issue by AlekSi** [aprelev/libgost15#6]
I can't think of use case where one should use Kuznechik (when required by the Russian government, for example) and can use GPL v3. Please consider changing a license to MIT-style one.

**Comment by aprelev** [comment]
The main problem being the open-source and same-license requirements?

**Comment by AlekSi** [comment]
Well, a lot of problems with a combination of proprietary and strong copyleft software. :) Also, almost impossible to certify in Russia.

**Comment by aprelev** [comment]
I switched to Apache 2.0. Almost as permissive as MIT ;)

**Comment by AlekSi** [comment]
Well, one problem with Apache 2.0 is [incompatibility with GPL 2](https://www.gnu.org/licenses/license-list.ru.html#apache2).
